# Generated by Django 4.2.7 on 2023-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_password', models.CharField(max_length=100)),
                ('server_address', models.CharField(max_length=100)),
                ('user_dn', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('search_base', models.CharField(max_length=100)),
            ],
        ),
    ]
