# Generated by Django 4.2.7 on 2023-11-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='default_password',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='search_base',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='user_dn',
        ),
    ]
