# Generated by Django 4.2.7 on 2023-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0002_remove_appsettings_default_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='default_password',
            field=models.CharField(default='1234qwer!@#$QWER', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='password',
            field=models.CharField(default='1234qwer!@#$QWER', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='search_base',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='server_address',
            field=models.CharField(default='12ghfrsdg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='user_dn',
            field=models.CharField(default='wadwaghr', max_length=100),
            preserve_default=False,
        ),
    ]
